const products = [
    { id: "1", name: "Αυτό είναι η αλλαγή στο Github (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "2", name: "Λουκανικα Χωριατικα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "3", name: "Νουμπουλο Καπνιστο Χοιρινο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "4", name: "Σαλαμι Chorizo (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "5", name: "Σουδακι έτοιμο 45mm (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "6", name: "Παξιμαδια Σταρενια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "7", name: "Ψωμακια Κουβερ ΚΤΨ Mix (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "8", name: "Ψωμι Τοστ Οικιακο Ολικης (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "9", name: "Κοτοπιτα ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "10", name: "Ψωμι Hot Dog 24cm ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "11", name: "Φοκατσια Τοματα - Ριγανη 1.8κιλ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "12", name: "Φυστικοβουτυρο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "13", name: "Βουτυρο Μεριδα President 10γρ 100/κιβ (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "14", name: "Γαλα Εβαπορε 410γρ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "15", name: "Γαλα Καρυδας Κ/Β (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "16", name: "Γαλα Μεριδα 7,5γρ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "17", name: "Γαλα Εβαπορε 304ml Ζαχαρουχο (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "18", name: "Κρεμα Γαλακτος Braun Φυτικη Ζαχαροπλαστικης (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "19", name: "Σαντιγυ Σπρει (τμχ) (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "20", name: "Κρεμα Γαλακτος Debic Ζωικη 1.5λιτ 35% (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "21", name: "Κρεμα Γαλακτος HALTA 1LT (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "22", name: "Μοτσαρελα Περλες 5γρ ΚΤΨ (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "23", name: "Μπλε Τυρι Δανιας (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "24", name: "Παρμεζανα Grana Padano 1/8 18Μηνων (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "25", name: "Κρεμα Τυριου (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "26", name: "Τυρι Φετα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "27", name: "Ξυγαλο (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "28", name: "Τυρι Κρεμα Γαλενι 220ΓΡ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "29", name: "Τυρι Τηνου (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "30", name: "Μοτσαρελα Φραντζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "31", name: "Τυρι Cottage (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "32", name: "Τυρι Μπατζος (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "33", name: "Χαλουμι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "34", name: "Τυρι Φετα Μεριδες (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "35", name: "Τριμμα Mix Σκληρων Τυριων (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "36", name: "Αμυλο Kαλαμποκιου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "37", name: "Γλυκοζη (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "38", name: "Κερασι Ολοκληρο Σε Ζελε Για Γεμιση (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "39", name: "Μαρασκινο Κοκκινο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "40", name: "Μιγμα Βαφλας (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "41", name: "Μιγμα Για Pancakes (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "42", name: "Φυλλο Κανταιφι Λευκο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "43", name: "Φυλλο Κρουστας ΚΤΨ (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "44", name: "Βουτυρο Κακαο (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "45", name: "Κερασι Μαυρο Ολοκληρο Σε Ζελε Για Γεμιση (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "46", name: "Κερασι Κοκκινο Ολοκληρο Σε Ζελε Για Γεμιση (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "47", name: "Βουτυρο 82% (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "48", name: "Μαργαρίνη με Αρωμα Βουτυρου 900ml(Σε Υγρη Μορφη) (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "49", name: "Βουτυρο 99,8% (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "50", name: "Πηκτινη για μαρμελαδες (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "51", name: "Λουκουμια Τριανταφυλλο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "52", name: "Επικαλυψη Ουδετερο Κρυο Ζελε (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "53", name: "Βαση Πιτσας 270γρ/30cm ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "54", name: "Σιμιγδαλι Ψιλο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "55", name: "Αμυγδαλο Σκονη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "56", name: "Μερεντα Παυλιδης (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "57", name: "Πραλινα Μεριδα 20γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "58", name: "Πραλινα Φουντουκιου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "59", name: "Σταγονες Σοκολατας Χονδρες  Dark 9401 (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "60", name: "Σοκολατα Γαλακτος Τζιαντουγια (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "61", name: "Ταρτακια Βουτυρου Στρογγυλα Γλυκα 4εκ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "62", name: "Κανολι Σφολιατας (200τμχ/κιβ) (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "63", name: "Κουβερτουρα Σταγονες Μαυρη Σοκολατα (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "64", name: "Πραλινα Αμυγδαλου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "65", name: "Ταρτακια Αλμυρα (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "66", name: "Μπισκοτα Cookies Σοκολατα (5kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "67", name: "Μπισκοτο Τριμμα Oreo (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "68", name: "Βουτημα Φραουλα (4kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "69", name: "Κουλουρακι Πλεξουδα Πορτοκαλι (4kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "70", name: "Μπισκοτο Βανιλια (3kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "71", name: "Μπισκοτα Cookies Διχρωμο (4kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "72", name: "Μπισκοτο Κουκις Τρουφα (4kg/κβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "73", name: "Πτι Φουρ Ισιο Βουτηχτο (4kg/κβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "74", name: "Πτι Φουρ Ισιο Ινδοκαρυδο (4kg/κβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "75", name: "Πτι Φουρ Ισιο Τρουφα (4kg/κβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "76", name: "Κουλουρακι Στρογγυλο Βουτυρου (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "77", name: "Πτι Φουρ Φραουλα (4kg/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "78", name: "Πτι Φουρ Τρουφα (4kg/κβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "79", name: "Πτι Φουρ Πραλινα (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "80", name: "Τυροπιτα Χωριατικη ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "81", name: "Σπανακοτυροπιτα Χωριατικη ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "82", name: "Μπαμπαδακια ΚΤΨ 75gr (35τεμ/κιβ) (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "83", name: "Βοσκοπιτα 200γρ ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "84", name: "Πητακια Τηγανιου 30γρ μυζηθρα-δυοσμο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "85", name: "Πητακια Τηγανιου 30γρ χορτα ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "86", name: "Σφακιανοπιτα 200γρ ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "87", name: "Μινι Κρουασαν Βουτυρου 25γρ (στοφ.) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "88", name: "Τριγωνακια Σιροπιασμενα (100τμχ/κιβ) (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "89", name: "Κιμαδοπιτα ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "90", name: "Μεσογειακη πιτα ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "91", name: "Παστα Φουντουκιου 100% (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "92", name: "Λουκουμια (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "93", name: "Παστα Πορτοκαλι (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "94", name: "Παστα Αμυγδαλο 100% 1kg (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "95", name: "Πραλινα Φυστικι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "96", name: "Τριγωνακι Σιροπιαστο 60γρ (48τμχ/κιβ) 2,8 κιλ (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "97", name: "Κοκορακι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "98", name: "Πρασσοτυροπιτα Τετραγωνη ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "99", name: "Μοσχου Κοκκαλα κομμενα (Bone Marrow) ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "100", name: "Μοσχου Φιλετο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "101", name: "Μοσχου Νουα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "102", name: "Χοιρινο Μπιφτεκι Μαυρου Χοιρου ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "103", name: "Χοιρινο Σουτζουκακι Με Μαυρο Χοιρο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "104", name: "Σουτζουκακι Horeca 90γρ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "105", name: "Σουτζουκακι Χοιρινό 100gr ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "106", name: "Αντσουγιες Φιλετο Σε Λαδι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "107", name: "Γαυρος Μαρινατος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "108", name: "Σκουμπρι Φιλετο Καπν. Σε Λαδι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "109", name: "Τσιροσαλατα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "110", name: "Συκα Αποξηραμενα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "111", name: "Βρωμη Νιφαδες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "112", name: "Choco Balls (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "113", name: "Corn Flakes (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "114", name: "Σιροπι Σφενδαμου (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "115", name: "Σιρόπι Σφενδάμου Flavor (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "116", name: "Ελαιολαδο Εξτρα Παρθενο (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "117", name: "Ελαιολαδο Εξτρα Παρθενο 20ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "118", name: "Ελιες Γεμιστες Αμυγδαλο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "119", name: "Ελιες Γεμιστες Πιπερια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "120", name: "Ελιες Γεμιστες Τυρι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "121", name: "Ελιες Θρουμπα Θασου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "122", name: "Ελιες Μαυρες Φετες (Ροδελα) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "123", name: "Ελιες Πρασινες 101-110 Mamouth (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "124", name: "Παστα Μαυρης Ελιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "125", name: "Ελιες Καλαμων 141-160 Giant (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "126", name: "Ελιες Καλαμων 161-180 Extra Jumbo (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "127", name: "Ζαχαρη Αχνη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "128", name: "Ζαχαρη Λευκη Stick 1000αδα (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "129", name: "Ζαχαρη Μαυρη Stick 1000αδα (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "130", name: "Φυλλο Λαζανια Κιτρινο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "131", name: "La Molisana Λινγκουινι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "132", name: "La Molisana Ταλιατελες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "133", name: "Φυλλο Λαζανια Πρασινο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "134", name: "La Molisana Spagheti No15 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "135", name: "La Molisana Παπαρδελες No105 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "136", name: "Τορτελινι Τυρι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "137", name: "Ζυμαρικα Χειροποιητα Strozzapreti ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "138", name: "La Molisana Νο94 Ριγκατονι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "139", name: "La Molisana Νο20 Πεννες Χ.Γλουτενη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "140", name: "La Molisana Linguine No6 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "141", name: "Ζυμαρικα Cappeleti Romagnoli ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "142", name: "Ζυμαρικα Giganti Con Funghi Porcini ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "143", name: "Ζυμαρικα Grancappelleto Romagnolo ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "144", name: "Grantortellone Verde Ricota Spinaci (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "145", name: "Ζωμος Αστακου 1lt Υγρο Hugli (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "146", name: "Ζωμος Υγρος Κοτας (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "147", name: "Ζωμος Υγρος Βοδινου (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "148", name: "Κομποστα Φρουτοσαλατα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "149", name: "Κομποστα Ανανας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "150", name: "Κομποστα Ροδακινο Φετα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "151", name: "Αμπελοφυλλα Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "152", name: "Πιπεριες Φλωρινης Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "153", name: "Τονος Σε Λαδι Κ/Β (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "154", name: "Φασολια Κοκκινα (Red beans) Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "155", name: "Πιπεριες Γεμιστες Με Κατσικισιο Τυρι 870γρ GRECI (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "156", name: "Πιπεριες Μινι Τρικολορε (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "157", name: "Φασολια Baked Beans Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "158", name: "Κριτσινια Ολικης (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "159", name: "Κριτσινια Σιτου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "160", name: "Κριτσινια Τυριου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "161", name: "Κριτσινια Χειροποιητα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "162", name: "Κρεπα Ετοιμη 25cm (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "163", name: "Κρεπα Παραδοσιακη 27cm (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "164", name: "Κρεπα Ετοιμη Φ18 ΚΤΨ (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "165", name: "Καπαρη Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "166", name: "Κουκουναρι Ψυχα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "167", name: "Ροφημα Σογιας (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "168", name: "Ντακος Κριθινος Μεγαλος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "169", name: "Ροφημα Αμυγδαλο (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "170", name: "Κινοα Πολυχρωμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "171", name: "Πληγουρι Χονδρο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "172", name: "Ταμπασκο Κoκκινο 60ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "173", name: "Ροφημα Καρυδας (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "174", name: "Μαρμελαδα Φραουλα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "175", name: "Μαρμελαδα Βερυκοκο Μεριδα Πλαστικο 20gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "176", name: "Μαρμελαδα Φραουλα Μεριδα Πλαστικο 20γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "177", name: "Μαρμελαδα Κερασι Μεριδες 20gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "178", name: "Μελι Μεριδα 28ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "179", name: "Αλατι Νιφαδες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "180", name: "Αλατι Κουβας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "181", name: "Αλατι Χονδρο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "182", name: "Ταχινι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "183", name: "Ταχινι Λευκο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "184", name: "Αλατι Ανθος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "185", name: "Αλατι Μεριδα (600τμχ) (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "186", name: "Πιπερι Μεριδα (600τμχ) (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "187", name: "Φαγοπυρο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "188", name: "Σαφραν 1γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "189", name: "Αγγουρακι Τουρσι-Κορνεσον (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "190", name: "Πληγουρι Μετριο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "191", name: "Πουρες Φραουλα ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "192", name: "Πουρες Λεμονι ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "193", name: "Πουρες Passion Fruit ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "194", name: "Πουρες Βυσσινο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "195", name: "Πουρες Βερυκοκο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "196", name: "Πουρες Ροδακινο Κοκκινο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "197", name: "Πουρες Γκουαβα ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "198", name: "Πουρες Μανγκο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "199", name: "Πουρες Βατομουρο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "200", name: "Πουρες Μουρο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "201", name: "Πουρες Καρυδα ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "202", name: "Πουρες Πρασινο Λεμονι / Λαιμ  ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "203", name: "Πουρες Μυρτιλο ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "204", name: "Πουρες Λαιμ ΠΟΥΛΠΑ ΚΤΨ (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "205", name: "Ρυζι Basmati (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "206", name: "Ρυζι Καρολινα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "207", name: "Φακες Ψιλες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "208", name: "Σαλτσα Ψαριου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "209", name: "Σαλτσα Worcestershire (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "210", name: "Σαλτσα Σογιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "211", name: "Σαλτσα Αγριορεπανο Horseradish 680ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "212", name: "Κετσαπ Tip Tree Γυαλινο Βαζο 28ml/72 (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "213", name: "Σαλτσα Για Πιτσα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "214", name: "Σαλτσα HP 430gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "215", name: "Σαλτσα HP 250gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "216", name: "Σαλτσα HP 465gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "217", name: "Σουπα Μανιταρι Κρεμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "218", name: "Σουπα Τοματα Κρεμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "219", name: "Σουπα Κοτοπουλο Κρεμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "220", name: "Σουπα Σπαραγγι Κρεμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "221", name: "Τοματα Λιαστη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "222", name: "Φρυγανια Τριμμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "223", name: "Ξυδια 380γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "224", name: "Ξυδι Κοκκινο 4λιτ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "225", name: "Ξυδι Λευκο 4λιτ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "226", name: "Ξυδι Κοκκινο 20ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "227", name: "Κοτοπουλο Φιλετο Στηθος ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "228", name: "Κοτοπουλο Σνιτσελ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "229", name: "Ταρτα Round Κακαο 80mm (108τεμ/κιβ) (ΤΕΜ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "230", name: "Φεγεντινη (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "231", name: "Αρακας ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "232", name: "Καροτο Κυβος ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "233", name: "Κουνουπιδι Κτψ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "234", name: "Μπαμιες ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "235", name: "Μπροκολο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "236", name: "Σπανακι Φυλλο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "237", name: "Spring Rolls Λαχανικων 25γρ ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "238", name: "Μπουγατσα ΚΤΨ Τυρι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "239", name: "Πιτα Σουβλακι Λευκη ΚΤΨ 17cm (10/πακ) (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "240", name: "Τορτιγιες 25cm 18τεμ/πακ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "241", name: "Spring Rolls Κοτοπουλο Hoi Sin (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "242", name: "Γαριδα Tempura ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "243", name: "Κροκετες Γαριδας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "244", name: "Spring Rolls Γαριδα Surimi (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "245", name: "Spring Rolls Χοιρινο Ginger (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "246", name: "Κωκακι ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "247", name: "Ροξακι ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "248", name: "Τουλουμπακι ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "249", name: "Κωκακι Σοκολατας ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "250", name: "Εκλαιρακι 50γρ ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "251", name: "Σεφταλιες ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "252", name: "Πατατα McCain 6x6 ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "253", name: "Βατομουρο Κοκκινο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "254", name: "Φραουλα ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "255", name: "Φρουτα Του Δασους ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "256", name: "Βυσσινο ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "257", name: "Sushi Ετοιμο ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "258", name: "Κουλουρι Ταχινι Σουσαμι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "259", name: "Κουλουρι Πορτοκαλιου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "260", name: "Κουλουρι Διχρωμο Πλακε (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "261", name: "Taco Shells 135gr (12τεμ/πακ) (ΠΑΚ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "262", name: "Κουλουρι Μαργαριτα Λεμονι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "263", name: "Κουλουρι Σμυρνεικο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "264", name: "Κουλουρι Χαλβα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "265", name: "Κουλουρι Ζεβρα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "266", name: "Κουλουρι Corn Flakes (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "267", name: "Χταποδι Καρπατσιο 80gr ΚΤΨ (ΤΕΜ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "268", name: "Φυλλο Σφολιατας ΚΤΨ (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "269", name: "Φυλλο Σφολιατας (ΒΟΥΤΥΡΟΥ) ΚΤΨ (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "270", name: "Πιπετες Διαφανες 4ml 100/πακ (ΠΑΚ)", category: "ΛΟΙΠΑ ΑΝΑΛΩΣΙΜΑ", supplier: "ΜΠΟΣΚΟΣ", supplierEmail: "" },
    { id: "271", name: "Μπουκιτσα Κοτοπουλο Φιλετακι Πανε ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "272", name: "Αρνισιο Κοτσι Πισινο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "273", name: "Αρνίσιο Ρολό ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "274", name: "Μοσχου Μαγουλα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "275", name: "Χοιρινο Κοτσι Μ/Ο Μ/Δ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "276", name: "Χοιρινο Λαιμος Α/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "277", name: "Χοιρινο Φιλετο - Ψαρονεφρι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "278", name: "Χοιρινο Κοντοσουβλι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "279", name: "Σουτζουκακι Αναμικτο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "280", name: "Χοιρινο Πανσετα Μαριναρισμενη Α/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "281", name: "Doner Γυρος Προψημενος (Σε φέτες) ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "282", name: "Χοιρινο Σουβλακι Λαιμου Χειροποιιτο 100γρ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "283", name: "Χοιρινο Λαιμος Κομμενος Μ/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "284", name: "Κοτοπουλο Μπουτι Μ/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "285", name: "Κοτοπουλο Μπουτι Α/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "286", name: "Κοτοπουλο Κοπανακι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "287", name: "Κοτοπουλο Κοντοσουβλι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "288", name: "Κοτοπουλο Σουβλακι 80γρ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "289", name: "Πιτα Σουβλακι Λευκη ΚΤΨ 17cm (10/πακ) (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "290", name: "Πατατα Country ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "291", name: "Πατατα McCain Crispers ΚΤΨ 5x2.5κιλ/κιβ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "292", name: "Πατατα McCain 9x9 ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΒΙΚΡΕ", supplierEmail: "" },
    { id: "293", name: "Μορταδελα Μπαστουνι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "294", name: "Προσουτο Crudo (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "295", name: "Ζαμπον Φετες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "296", name: "Λουκανικα Τσουμαγιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "297", name: "Λουκανικα Χωριατικα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "298", name: "Λουκανικα Γαλοπουλας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "299", name: "Λουκανικα Πεπερονι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "300", name: "Απακι Χοιρινο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "301", name: "Παστο Μανης Συγκλινο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "302", name: "Παστουρμας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "303", name: "Προσουτο Φετες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "304", name: "Λουκανικα Καραμανλιδικα Μοσχαρισια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "305", name: "Παξιμαδια Σταρενια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "306", name: "Ψωμι Τοστ 12χ12 Σιτου (Γιγας - 1 Κιλ) (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "307", name: "Ψωμι Τοστ 12χ12 Μαυρο (Γιγας - 1 Κιλ) (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "308", name: "Ψωμι Τοστ Οικιακο Λευκο (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "309", name: "Ψωμι Τοστ Οικιακο Ολικης (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "310", name: "Χαλβας Σοκολατα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "311", name: "Μαργαρινη Μεριδα 10γρ Adoro 10gr 96/κιβ (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "312", name: "Γαλα Εβαπορε 410γρ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "313", name: "Γαλα Εβαπορε 397γρ Ζαχαρουχο (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "314", name: "Γαλα Μεριδα 7,5γρ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "315", name: "Γαλα Μακρας Διαρκειας 1,5% (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "316", name: "Γαλα Μακρας Διαρκειας 3,5% (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "317", name: "Γιαουρτι Αγελαδινο Στραγγιστο 5% (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "318", name: "Τυρι Γκοργκοντζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "319", name: "Ανθοτυρο (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "320", name: "Γκουντα Φραντζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "321", name: "Κεφαλοτυρι Κεφαλι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "322", name: "Μανουρι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "323", name: "Μπλε Τυρι Δανιας (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "324", name: "Παρμεζανα Grana Padano 1/8 18Μηνων (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "325", name: "Τυρι Ταλαγανι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "326", name: "Τυρι Φετα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "327", name: "Μοτσαρελα Φραντζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "328", name: "Τυρι Μετσοβονε (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "329", name: "Λαδοτυρι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "330", name: "Τυρι Φετα Αγελαδινη Τριμα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "331", name: "Μυζηθρα Ξυνη (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "332", name: "Κεφαλοτυρι Σαγανακι Φρατζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "333", name: "Τυρι Νιβατο Μαλακο (Γλυκοξινο) (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "334", name: "Χαλουμι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "335", name: "Γραβιερα Ναξου (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "336", name: "Τσενταρ Κοκκινο Φραντζολα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "337", name: "Κασερι ΠΟΠ Ελασσονας (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "338", name: "Γραβιερα Κρητης (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "339", name: "Τυρι Chevre με Κρουστα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "340", name: "Κασερι Ξανθης ΠΟΠ (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "341", name: "Τυρι Φετα Μεριδες (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "342", name: "Παρμεζανα Grana Padano Ολοκληρο Κεφαλι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "343", name: "Τυρι Σαν Μιχαλη (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "344", name: "Πολεντα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "345", name: "Γλυκο Κουταλιου Βυσσινο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "346", name: "Γλυκο Κουταλιου Συκο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "347", name: "Γλυκο Κουταλιου Σταφυλι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "348", name: "Μερεντα Παυλιδης (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "349", name: "Αρνισια Παιδακια Γαλλικης Κοπης ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "350", name: "Αρνισια Χερακια ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "351", name: "Αρνισιο Μπουτι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "352", name: "Κουνελι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "353", name: "Αρνισιο Κοτσι Πισινο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "354", name: "Μοσχου Κοκκαλα κομμενα (Bone Marrow) ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "355", name: "Μοσχου Μαγουλα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "356", name: "Μοσχαρι Black Angus Striploin ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "357", name: "Μοσχου Rib Eye Roll Angus Ουρουγουαης ΔΡΑΚΟΥΛΗΣ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "358", name: "Χοιρινο Λαιμος Α/Ο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "359", name: "Κοτοπουλο Γυρος Προψημενος ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "360", name: "Χοιρινο Γυρος Προψημενος ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "361", name: "Χοιρινη Tomahawk ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "362", name: "Χοιρινο Μπριζολακι Α/Ο ΔΡΑΚΟΥΛΗΣ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "363", name: "Χοιρινα Μαγουλα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "364", name: "Αντσουγιες Φιλετο Σε Λαδι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "365", name: "Σκουμπρι Φιλετο Καπν. Σε Λαδι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "366", name: "Τσιροσαλατα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "367", name: "Τονολακερδα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "368", name: "Χελι Καπνιστο Φιλετο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "369", name: "Honey Rings (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "370", name: "Choco Balls (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "371", name: "Corn Flakes (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "372", name: "Γκρανολα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "373", name: "Σουσαμελαιο Sesame Oil (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "374", name: "Ηλιελαιο (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "375", name: "Λαδι Λευκης Τρουφας (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "376", name: "Ελαιολαδο Εξτρα Παρθενο 20ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "377", name: "Ελιες Μαυρες Φετες (Ροδελα) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "378", name: "Παστα Μαυρης Ελιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "379", name: "Ελιες Μαυρες Αμφισσης 121 - 140 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "380", name: "Ζαχαρη Αχνη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "381", name: "Ζαχαρη Μαυρη Κιλου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "382", name: "Κους Κους (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "383", name: "Κριθαρακι Μετριο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "384", name: "Ζυμαρικο Κοφτο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "385", name: "Ζυμαρικο Πεννες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "386", name: "Ζυμαρικα Νο6 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "387", name: "Ζυμαρικο Νο2 (Παστιτσιο) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "388", name: "Φιδες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "389", name: "De Cecco Linguini No 7 3κιλ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "390", name: "De Cecco Spagheti No12 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "391", name: "De Cecco Gniochi Πατατας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "392", name: "Ζυμαρικο Σπαγγετι Νο6 (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "393", name: "De Cecco Παπαρδελες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "394", name: "De Cecco Ταλιατελες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "395", name: "Barilla Penne Rigate (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "396", name: "Νιοκι Πατατας De Cecco (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "397", name: "Ζωμος Παστα Κοτας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "398", name: "Ζωμος Παστα Βοδινου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "399", name: "Κομποστα Φρουτοσαλατα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "400", name: "Κομποστα Ανανας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "401", name: "Κομποστα Ροδακινο Φετα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "402", name: "Αμπελοφυλλα Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "403", name: "Porcini Μανιταρια Αφυδατομενα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "404", name: "Πιπεριες Φλωρινης Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "405", name: "Τονος Σε Λαδι Κ/Β (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "406", name: "Φασολια Baked Beans Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "407", name: "Κριταμο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "408", name: "Καπαρη Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "409", name: "Μελανι Σουπιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "410", name: "Πουρες Πατατας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "411", name: "Ροφημα Σογιας (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "412", name: "Χαλβας Βανιλια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "413", name: "Ταμπασκο Πρασινο 60ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "414", name: "Νουντλς Αυγου (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "415", name: "Ντακος Κριθινος Μεγαλος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "416", name: "Χαβιαρι Σολωμου 50γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "417", name: "Ροφημα Αμυγδαλο (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "418", name: "Κινοα Πολυχρωμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "419", name: "Τραχανας Ξινος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "420", name: "Πληγουρι Χονδρο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "421", name: "Won Ton Φυλλα ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "422", name: "Miso Soy Bean Paste (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "423", name: "Ταμπασκο Κoκκινο 60ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "424", name: "Ροφημα Καρυδας (ΛΙΤ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "425", name: "Μαγιονεζα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "426", name: "Μαγιονεζα Dressing / Αναπληρωμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "427", name: "Vegan Μαγιονεζα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "428", name: "Μαρμελαδα Βερυκοκο Μεριδα Πλαστικο 20gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "429", name: "Μαρμελαδα Φραουλα Μεριδα Πλαστικο 20γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "430", name: "Μαρμελαδα Κερασι Μεριδες 20gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "431", name: "Μελι Μεριδα 100Αδα (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "432", name: "Μελι Μεριδα 28ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "433", name: "Αλατι Νιφαδες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "434", name: "Αλατι Κουβας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "435", name: "Chia Seeds (Τσια) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "436", name: "Αυγοταραχο Τριμμα 50γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "437", name: "Αυγοταραχο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "438", name: "Αυγα Σολομου (Μπρικ) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "439", name: "Αυγα Χρυσης Ρεγγας (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "440", name: "Αγγουρακι Τουρσι-Κορνεσον (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "441", name: "Πικλες Τουρσι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "442", name: "Πιπερακι Τουρσι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "443", name: "Πιπεροριζα Τουρσι σε φετες (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "444", name: "Χαβιαρι Ρεγγας 55γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "445", name: "Σαλτσα Hoisin (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "446", name: "Σαλτσα Πέστο (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "447", name: "Φασολια Μαυροματικα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "448", name: "Ρεβυθια Μετρια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "449", name: "Ρυζι Basmati (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "450", name: "Ρυζι Αρμποριο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "451", name: "Ρυζι Καρολινα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "452", name: "Ρυζι Μπονετ (Κιτρινο) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "453", name: "Φακες Belluga (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "454", name: "Φακες Ψιλες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "455", name: "Φασολια Γιγαντες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "456", name: "Φασολια Μετρια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "457", name: "Ρυζι Μαυρο (Αγριο) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "458", name: "Φαβα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "459", name: "Μελιτζανοσαλατα Χωριατικη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "460", name: "Ουγγαρεζα Ετοιμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "461", name: "Ταραμοπολτος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "462", name: "Ταραμοσαλατα Λευκη Ετοιμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "463", name: "Τυροσαλατα Ετοιμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "464", name: "Τζατζικι Ετοιμο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "465", name: "Ταραμοπολτος Λευκος (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "466", name: "Ταραμοσαλατα Κοκκινη Ετοιμη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "467", name: "Κρεμα Γαριδας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "468", name: "Κετσαπ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "469", name: "Μουσταρδα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "470", name: "Μουσταρδα Dijon (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "471", name: "Σαλτσα Worcestershire (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "472", name: "Σαλτσα Ντεμι Γκλας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "473", name: "Μους Αβοκαντο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "474", name: "Σαλτσα Sriracha (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "475", name: "Σαλτσα BBQ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "476", name: "Mιγμα BBQ 680gr (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "477", name: "Τοματα Λιαστη (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "478", name: "Τοματοπολτος Διπλης Συμπ/σης (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "479", name: "Κονκασε (Τομ.Ψιλοκομμενο) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "480", name: "Φρυγανια Τριμμα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "481", name: "Πανκο (Panko) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "482", name: "Μηλοξυδο Χυμα (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "483", name: "Κρεμα Μαυρη Τρουφα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "484", name: "Ξυδια 380γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "485", name: "Ξυδι Βαλσαμικο Λευκο (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "486", name: "Ξυδι Ρυζιου (MIRIN) (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "487", name: "Χυμος Λεμονιου 380γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "488", name: "Instant Ton Yum Παστα 24*454γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "489", name: "Ξυδι Βαλσαμικο Μαυρο 4λιτρο (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "490", name: "Ξυδι Βαλσαμικο 20ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "491", name: "Ξυδι Κοκκινο 4λιτ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "492", name: "Κρεμα Βαλσαμικο Διαφορες Γευσεις 250ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "493", name: "Ξυδι Βαλσαμικο με Ροδι 250ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "494", name: "Ξυδι Λευκο 4λιτ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "495", name: "Κρεμα Βαλσαμικο Συκο 250ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "496", name: "Κρεμα Βαλσαμικο Ροδι 250ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "497", name: "Ξυδι Βαλσαμικο Μαυρο (ΛΙΤ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "498", name: "Ξυδι Κοκκινο 20ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "499", name: "Κρεμα Βαλσαμικο Classic 250ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "500", name: "Κοτοπουλο Κοκκαλα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "501", name: "Κοτοπουλο Φιλετο Στηθος ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "502", name: "Κοτοπουλο Φιλετο Στηθος Α (Ελληνικο) ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "503", name: "Κοτοπουλο Κοπανακι ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "504", name: "Vegan Μπιφτεκι Burger ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "505", name: "Vegan Nuggets ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "506", name: "Καλαμποκι Baby κονσερβα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "507", name: "Τορτιγιες 25cm 18τεμ/πακ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "508", name: "Σεφταλιες ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "509", name: "Τορτιγιες 25cm 6τεμ/πακ (ΠΑΚ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "510", name: "Μυδια Μισο Κελυφος ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "511", name: "Μυδια Ψυχα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "512", name: "Ξιφιας Φετα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "513", name: "Χτενια Ψυχα ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "514", name: "Γαριδα Vanamei 20-30 ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "515", name: "Γαριδα Vanamei 10-20 ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "516", name: "Θραψαλο Καθαρισμενο 200-400 ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "517", name: "Γλυκο Κουταλιου Πορτοκαλι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "518", name: "Γλυκο Κουταλιου Κερασι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "ΑΝΑΝΙΑΔΗΣ", supplierEmail: "" },
    { id: "519", name: "Ζαμπον Πικ Νικ Μπαστουνι (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "520", name: "Ζαμπον Πικ Νικ Φετες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "521", name: "Τσιαπατα ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "522", name: "Μπαγκετα Λευκη 27εκ ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "523", name: "Μπαγκετα Ολικης 27εκ ΚΤΨ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "524", name: "Bao Buns ΚΤΨ Χυμα (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "525", name: "Γιαουρτι Στραγγιστο 10% (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "526", name: "Ημισκληρο Τυρι (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "527", name: "Μπλε Τυρι Δανιας (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "528", name: "Τυρι Φετα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "529", name: "Τυρι Φετα Αγελαδινη Τριμα (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "530", name: "Μοτσαρελα Σε Νερο 125γρ (ΤΕΜ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "531", name: "Τυρι Φετα Μεριδες (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "532", name: "Μπλε Τυρι ΚΥΑΝΟ (ΚΙΛ)", category: "ΓΑΛΑΚΤΟΚΟΜΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "533", name: "Σιμιγδαλι Χοντρο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "534", name: "Γλυκο Κουταλιου Βυσσινο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "535", name: "Γλυκο Κουταλιου Συκο (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "536", name: "Σιμιγδαλι Ψιλο (ΚΙΛ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "537", name: "Σιροπι Παγωτου Σοκολατα (ΛΙΤ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "538", name: "Σιροπι Παγωτου Φραουλα (ΛΙΤ)", category: "ΖΑΧΑΡΟΠΛΑΣΤΙΚΗ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "539", name: "Γκρανολα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "540", name: "Choco Shells (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "541", name: "Αμπελοφυλλα Κ/Β (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "542", name: "Μαγιονεζα Μεριδα Hellmanns 198τεμ (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "543", name: "Μαγιονεζα Hellmans Γυαλινο Βαζο 33γρ (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "544", name: "Φασολια Μαυροματικα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "545", name: "Ρεβυθια Μετρια (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "546", name: "Φακες Belluga (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "547", name: "Φακες Ψιλες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "548", name: "Φασολια Γιγαντες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "549", name: "Φακες Κοκκινες (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "550", name: "Κετσαπ Μεριδα Hellmanns 198τεμ (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "551", name: "Σαλτσα Σογιας (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "552", name: "Μουσταρδα Μεριδα Hellmanns 198τεμ (ΚΙΒ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "553", name: "Κετσαπ Hellmanns Γυαλινο Βαζο 33ml/80 (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "554", name: "Σαλτσα Για Πιτσα (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "555", name: "Σαλτσα Κοκκινη Καυτερη 100ml (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "556", name: "Μουσταρδα Hellmanns Γυαλινο Βαζο 33γρ/80 (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "557", name: "Τοματοπολτος Διπλης Συμπ/σης (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "558", name: "Κονκασε (Τομ.Ψιλοκομμενο) (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "559", name: "Κοτοπουλο ΚΤΨ Κορντον Μπλου (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "560", name: "Κοτοπουλο Σνιτσελ ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "561", name: "Καλαμποκι Σπυρι ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "562", name: "Πιτα Σουβλακι Λευκη ΚΤΨ 17cm (10/πακ) (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "563", name: "Πιτα Σουβλακι Λευκη ΚΤΨ 10cm 32*10αδα (ΤΕΜ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "564", name: "Πατατα Country ΚΤΨ (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "565", name: "Σολομος Καπνιστος Φιλετο ΚΤΨ (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "566", name: "Σουπια Καθαρισμενη ΚΤΨ U1 IQF (ΚΙΛ)", category: "ΚΡΕΑΤΙΚΑ - ΨΑΡΙΚΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
    { id: "567", name: "Γλυκο Κουταλιου Πορτοκαλι fgdfgfgfgfdgfgfgf (ΚΙΛ)", category: "ΛΟΙΠΑ ΤΡΟΦΙΜΑ", supplier: "THASSOSFOODS", supplierEmail: "" },
];